version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=openweather
      - MYSQL_ROOT_PASSWORD=adminpwd
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-db: